### ISSUE TITLE
test_get_signature_with_complex_non_unicode_payload has different results between py2 & py3

### ISSUE THREAD

**Issue by taddeimania** [madisona/apysigner#6]
Python 3.4 test output:
```python
======================================================================
FAIL: test_get_signature_with_complex_non_unicode_payload (__main__.SignatureMakerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_apysigner.py", line 92, in test_get_signature_with_complex_non_unicode_payload
    self.assertEqual(expected_signature, signature)
AssertionError: 'virZB7ImBMpkgbmAJUVmhIkeX50CJ2iRHjA6IyQwgV4=' != '6yjt2ptXRKOL4JTU8tuVoR5NipllBgI9HLNXIvpKdc8='
```

Python 2.7 test output:
```python
======================================================================
FAIL: test_get_signature_with_complex_non_unicode_payload (__main__.SignatureMakerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_apysigner.py", line 92, in test_get_signature_with_complex_non_unicode_payload
    self.assertEqual(expected_signature, signature)
AssertionError: 'virZB7ImBMpkgbmAJUVmhIkeX50CJ2iRHjA6IyQwgV4=' != u'XmrJ7QAhlLgsOJR9JWoE3UwCwF61l4_A_dSkjonlqQM='
```
Not sure why this is happening

refs https://github.com/madisona/apysigner/pull/4

**Comment by taddeimania** [comment]
I think I figured this one out!

In python 2.x unicode strings are specially marked with the leading `u` character.  In python 3.x it's just assumed they are unicode friendly.  So when a complex object gets passed in to urlencode it includes the `u` characters in python 2.x.  See below:

2.x
```
'/accounts/user/add/?agency=None&company=9690&coverages=%5B%28u%27construction_type%27%2C+u%27%27%29%2C+%28u%27coverage_amount%27%2C+u%2710'
```

3.x
```
'/accounts/user/add/?agency=None&company=9690&coverages=%5B%28%27construction_type%27%2C+%27%27%29%2C+%28%27coverage_amount%27%2C+%2710'
```

See just after `construction_type` there is some encoding with the letter `u` in there!

**Comment by taddeimania** [comment]
This is an interesting problem because it could in fact (down the road) cause services that cannot talk to other services because of a python version incompatibility.  Interesting indeed.

**Comment by taddeimania** [comment]
Closing py3 compat pull request.

I do believe this exposes a bug at a very low level in that the encoder is including the `u''` in the string to be encoded.
